build: Release Please to control tests module too (#4771)
Release Please updates the versions listed in the manifest only (Related: https://github.com/googleapis/release-please/issues/1453). The tests module is not touched by Release Please. This pull request attempts to include the module into the scope of Release Please

# The Problem to Solve

Because of this gap, currently the tests/dependency-convergence module fails when we create a new version:

```
[INFO] Scanning for projects...
Error: ] Some problems were encountered while processing the POMs:
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-datastream:jar is missing. @ line 146, column 18
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-dataplex:jar is missing. @ line 150, column 18
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-optimization:jar is missing. @ line 285, column 17
 @ 
Error:  The build could not read 1 project -> [Help 1]
Error:    
Error:    The project com.google.cloud:full-convergence-check:0.174.0 (/home/runner/work/java-cloud-bom/java-cloud-bom/tests/dependency-convergence/pom.xml) has 3 errors
Error:      'dependencies.dependency.version' for com.google.cloud:google-cloud-datastream:jar is missing. @ line 146, column 18
Error:      'dependencies.dependency.version' for com.google.cloud:google-cloud-dataplex:jar is missing. @ line 150, column 18
Error:      'dependencies.dependency.version' for com.google.cloud:google-cloud-optimization:jar is missing. @ line 285, column 17
```

The error occurs in tests/dependency-convergence directory with `mvn -B -V -ntp validate`.

The google-cloud-bom version in the test pom.xml is not updated. https://github.com/googleapis/java-cloud-bom/blob/196198c62a720ff364e0b547c2f7a73783d884e5/tests/dependency-convergence/pom.xml#L26

It should have pointed to "0.175.0".